Fix number_from_string() function in cnex
ghewgill/neon-lang pull request #326
Opened 2020-11-06 20:24 UTC by gitlarryf

2020-11-08 09:28 UTC, ghewgill commented
This also needs to include the corresponding test.

2020-12-31 01:35 UTC, ghewgill requested changes
This also needs to include the corresponding test.

2021-01-04 23:58 UTC, ghewgill requested changes

2021-01-04 23:58 UTC, ghewgill commented on exec/cnex/number.c
>  Number number_from_string(char *s)
This should be `const char *`.

2021-01-06 01:09 UTC, gitlarryf commented on exec/cnex/number.c
>  Number number_from_string(char *s)
Changed.

2021-01-06 08:21 UTC, merged